title:              和风的博客
email:              hiccphp@qq.com
description:        Only love and music can not live up to
author:             hiccphp
baseurl:            ""
url:                "https://hsc2019.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    hsc2019
facebook_username:  StartBootstrap
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
highlighter:        rouge
markdown:           kramdown
kramdown:
  input:              GFM
  syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
