title:              和风的博客
email:              hiccphp@qq.com
description:        Only love and music can not live up to
author:             hiccphp
baseurl:            ""
url:                "https://hsc2019.github.io"

# Social Profiles
email: hiccphp@qq.com
twitter_username:   
github_username:    hsc2019
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
highlighter:        rouge
markdown:           kramdown
kramdown:
  input:              GFM
  syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# gitalk settings
comment_gitalk_repo: hsc2019.github.io
comment_gitalk_clientId: 0914b5fe499f3065ab70
comment_gitalk_clientSecret: d0509245cf3d7d267bbe67877f6cecd4c274a36c
